# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GH Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: yarn install --production
    - run: yarn build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
